# -*- coding: utf-8 -*-
"""02_string_kalimat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkvR5hCWG2yHDKU_DFI0LZKoZ3fjj9sb
"""

K1 = "Saya tak 'kan menyerah."
K2 = 'Ia berkata, "Aku menyayangimu."'
K3 = "\"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!\""
K4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(K1)
print(K2)
print(K3)
print(K4)