# -*- coding: utf-8 -*-
"""04_nip_asn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZqPltW23woIuEoDzvWpQ5lCKHwkg8SQ
"""

# Skenario 1 (Input Normal)
print("Skenario 1 (Input Normal)")

# Input langsung ditentukan di dalam kode
NIP_input = "199301212019031010"
print("Input NIP:", NIP_input)

# Memotong string
tahun = NIP_input[0:4]
bulan_str = NIP_input[4:6]
tanggal_str = NIP_input[6:8]

# Konversi tanggal ke angka
tanggal_angka = int(tanggal_str)

# Percabangan nama bulan
if bulan_str == "01":
    nama_bulan = "Januari"
elif bulan_str == "02":
    nama_bulan = "Februari"
elif bulan_str == "03":
    nama_bulan = "Maret"
elif bulan_str == "04":
    nama_bulan = "April"
elif bulan_str == "05":
    nama_bulan = "Mei"
elif bulan_str == "06":
    nama_bulan = "Juni"
elif bulan_str == "07":
    nama_bulan = "Juli"
elif bulan_str == "08":
    nama_bulan = "Agustus"
elif bulan_str == "09":
    nama_bulan = "September"
elif bulan_str == "10":
    nama_bulan = "Oktober"
elif bulan_str == "11":
    nama_bulan = "November"
elif bulan_str == "12":
    nama_bulan = "Desember"
else:
    nama_bulan = "(Bulan Tidak Valid)"

print("Tanggal Lahir:", tanggal_angka, nama_bulan, tahun)

# Skenario 2 (Kondisi Khusus)
print("Skenario 2 (Kondisi Khusus)")

# Input langsung ditentukan di dalam kode
NIP_input = "200008052024012003"
print("Input NIP:", NIP_input)

# Memotong string
tahun = NIP_input[0:4]
bulan_str = NIP_input[4:6]
tanggal_str = NIP_input[6:8]

# Konversi tanggal ke angka
tanggal_angka = int(tanggal_str)

# Percabangan nama bulan
if bulan_str == "01":
    nama_bulan = "Januari"
elif bulan_str == "02":
    nama_bulan = "Februari"
elif bulan_str == "03":
    nama_bulan = "Maret"
elif bulan_str == "04":
    nama_bulan = "April"
elif bulan_str == "05":
    nama_bulan = "Mei"
elif bulan_str == "06":
    nama_bulan = "Juni"
elif bulan_str == "07":
    nama_bulan = "Juli"
elif bulan_str == "08":
    nama_bulan = "Agustus"
elif bulan_str == "09":
    nama_bulan = "September"
elif bulan_str == "10":
    nama_bulan = "Oktober"
elif bulan_str == "11":
    nama_bulan = "November"
elif bulan_str == "12":
    nama_bulan = "Desember"
else:
    nama_bulan = "(Bulan Tidak Valid)"

print("Tanggal Lahir:", tanggal_angka, nama_bulan, tahun)

# Skenario 3 (Input Tidak Valid)
print("Skenario 3 (Input Tidak Valid)")

# Input langsung ditentukan di dalam kode
NIP_input = "199599122018011001"
print("Input NIP:", NIP_input)

# Memotong string
tahun = NIP_input[0:4]
bulan_str = NIP_input[4:6]
tanggal_str = NIP_input[6:8]

# Konversi tanggal ke angka
tanggal_angka = int(tanggal_str)

# Percabangan nama bulan
if bulan_str == "01":
    nama_bulan = "Januari"
elif bulan_str == "02":
    nama_bulan = "Februari"
elif bulan_str == "03":
    nama_bulan = "Maret"
elif bulan_str == "04":
    nama_bulan = "April"
elif bulan_str == "05":
    nama_bulan = "Mei"
elif bulan_str == "06":
    nama_bulan = "Juni"
elif bulan_str == "07":
    nama_bulan = "Juli"
elif bulan_str == "08":
    nama_bulan = "Agustus"
elif bulan_str == "09":
    nama_bulan = "September"
elif bulan_str == "10":
    nama_bulan = "Oktober"
elif bulan_str == "11":
    nama_bulan = "November"
elif bulan_str == "12":
    nama_bulan = "Desember"
else:
    nama_bulan = "(Bulan Tidak Valid)"

print("Tanggal Lahir:", tanggal_angka, nama_bulan, tahun)