# -*- coding: utf-8 -*-
"""04_Tanggal_lahir_NIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjVz5JTIuXz0LCb1evorllfCoWOnNMtq
"""

# Program Untuk Mengekstrak Tanggal Lahir dari NIP ASN
NIP = input("Masukkan NIP ASN: ")

# Validasi panjang input minimal 8 digit awal
if len(NIP) < 8:
    print("Error: NIP yang dimasukkan terlalu pendek (minimal 8 digit).")
else:
    # Proses ekstraksi komponen tanggal lahir
    tahun = NIP[0:4]
    bulan_str = NIP[4:6]
    tanggal = NIP[6:8]

    # Percabangan untuk konversi nama bulan
    if bulan_str == "01":
        bulan = "Januari"
    elif bulan_str == "02":
        bulan = "Februari"
    elif bulan_str == "03":
        bulan = "Maret"
    elif bulan_str == "04":
        bulan = "April"
    elif bulan_str == "05":
        bulan = "Mei"
    elif bulan_str == "06":
        bulan = "Juni"
    elif bulan_str == "07":
        bulan = "Juli"
    elif bulan_str == "08":
        bulan = "Agustus"
    elif bulan_str == "09":
        bulan = "September"
    elif bulan_str == "10":
        bulan = "Oktober"
    elif bulan_str == "11":
        bulan = "November"
    elif bulan_str == "12":
        bulan = "Desember"
    else:
        bulan = "Tidak Valid"

    # Menampilkan hasil output program
    if bulan != "Tidak Valid":
        print(f"ASN tersebut lahir pada tanggal: {tanggal} {bulan} {tahun}")
    else:
        print("Error: Dua digit bulan pada NIP tidak valid.")