# -*- coding: utf-8 -*-
"""05_akar_bilangan_real.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xV5pNGxIUZPP7WopFYV-qym3xukgP3L3
"""

# Input koefisien
a = 1
b = 2
c = 3

# Hitung diskriminan
discriminant = b**2 - 4*a*c

# Cek jenis akar
if discriminant > 0:
    x1 = (-b + math.sqrt(discriminant)) / (2*a)
    x2 = (-b - math.sqrt(discriminant)) / (2*a)
    print("Persamaan memiliki dua akar real berbeda:")
    print(f"x1 = {x1:.3f}")
    print(f"x2 = {x2:.3f}")

elif discriminant == 0:
    x = -b / (2*a)
    print("Persamaan memiliki dua akar real kembar:")
    print(f"x1 = x2 = {x:.3f}")

else:
    print("Persamaan hanya memiliki akar-akar imajiner.")